//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lopux.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> material_type_id { get; set; }
        public Nullable<int> count_in_package { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> count_in_stock { get; set; }
        public Nullable<int> min_balance { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual material_type material_type { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
